//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cl.ingennia.wishmaker.adapter;

import android.app.Activity;
import android.content.Context;
import android.widget.TextView;
import cl.ingennia.wishmaker.R.id;
import cl.ingennia.wishmaker.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class MeteorItemView_
    extends MeteorItemView
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public MeteorItemView_(Context context) {
        super(context);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        title = ((TextView) findViewById(id.title));
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.item_meteorview, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static MeteorItemView build(Context context) {
        MeteorItemView_ instance = new MeteorItemView_(context);
        instance.onFinishInflate();
        return instance;
    }

}
