common: &common
  adapter: postgis
  encoding: UTF-8
  pool: 5
  username: postgres
  password: admin
  schema_search_path: "public,postgis"
  script_dir: /Library/PostgreSQL/9.1/share/postgresql/contrib/postgis-1.5/
  port: 5432
  host: localhost
  postgis_extension: true
  template: template_postgis

development:
  <<: *common
  database: wishmaker_backend_development
  
test:
  <<: *common
  database: wishmaker_backend_test

production:
  <<: *common
  database: wishmaker_backend_production

