//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cl.ingennia.wishmaker.rest;

import cl.ingennia.wishmaker.domain.Meteor;
import cl.ingennia.wishmaker.domain.Wish;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.converter.json.MappingJacksonHttpMessageConverter;
import org.springframework.web.client.RestTemplate;

public class RestClient_
    implements RestClient
{

    private RestTemplate restTemplate;
    private String rootUrl;

    public RestClient_() {
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new MappingJacksonHttpMessageConverter());
        rootUrl = "http://172.16.0.66";
    }

    @Override
    public Meteor[] getAllMeteors() {
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        return restTemplate.exchange(rootUrl.concat("/meteors.json"), HttpMethod.GET, requestEntity, Meteor[].class).getBody();
    }

    @Override
    public Wish[] getAllWishes() {
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        return restTemplate.exchange(rootUrl.concat("/wishes.json"), HttpMethod.GET, requestEntity, Wish[].class).getBody();
    }

}
