//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cl.ingennia.wishmaker.broadcastreceiver;

import android.app.NotificationManager;
import android.content.Context;
import android.content.Intent;

public final class LocationReceiver_
    extends LocationReceiver
{

    private Context context_;

    private void init_() {
        notificationManager = ((NotificationManager) context_.getSystemService(Context.NOTIFICATION_SERVICE));
    }

    @Override
    public void onReceive(Context context, Intent intent) {
        context_ = context;
        init_();
        super.onReceive(context, intent);
    }

}
